"""Contract tests against the request the Go agent actually sends.

testdata/analyze_request.json is generated by internal/reasoning/client_test.go from the
agent's own structs. If either side changes field names or units, one of the suites fails.
"""
import json
import os
import sys

from fastapi.testclient import TestClient

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from main import app
from reasoner import analyze_workloads

FIXTURE = os.path.join(os.path.dirname(__file__), "..", "..", "testdata", "analyze_request.json")

client = TestClient(app)


def load_fixture():
    with open(FIXTURE, encoding="utf-8") as f:
        return json.load(f)


def by_target_and_action(recs):
    return {(r["target"], r["action"]): r for r in recs}


def test_agent_request_is_accepted_and_analysed():
    response = client.post("/api/v1/analyze", json=load_fixture())
    assert response.status_code == 200, response.text
    recs = by_target_and_action(response.json())

    # Over-provisioned: 0.2 cores per replica against a 1-core request.
    down = recs[("shop/api", "RIGHTSIZE_CPU_DOWN")]
    assert down["status"] == "Pending"
    assert down["expected_savings"] > 0
    proposed = json.loads(down["proposed_state"])
    assert proposed["cpu_requests"] == 0.7  # capped at a 30% step-down

    # Hot: 0.475 cores per replica against a 0.5-core request.
    assert recs[("shop/checkout", "SCALE_UP_CPU_SAFETY")]["status"] == "Pending"

    # Idle but in a protected namespace.
    grafana = recs[("monitoring/grafana", "RIGHTSIZE_CPU_DOWN")]
    assert grafana["status"] == "Rejected"
    assert "PolicyRejected:ExcludedNamespace" in grafana["rule_trace"]


def test_history_from_agent_is_used():
    workload = load_fixture()["namespaces"]["shop"]["workloads"]["api"]
    response = client.post("/api/v1/forecast", json=workload)
    assert response.status_code == 200, response.text
    # Eight history points per series reach full telemetry quality.
    assert response.json()["telemetry_quality"] == 1.0


def test_usage_is_compared_per_replica():
    # 3 replicas each using half of a 1-core request: neither over- nor under-provisioned.
    snapshot = {"namespaces": {"shop": {"workloads": {"web": {
        "replicas": 3, "cpu_requests": 1.0, "cpu_usage": 1.5,
        "cpu_history": [1.5, 1.5, 1.5, 1.5, 1.5],
    }}}}}
    assert analyze_workloads(snapshot) == []


def test_excluded_workloads_are_skipped():
    snapshot = load_fixture()
    snapshot["namespaces"]["shop"]["workloads"]["api"]["is_excluded"] = True
    targets = {r["target"] for r in analyze_workloads(snapshot)}
    assert "shop/api" not in targets
    assert "shop/checkout" in targets

